platform :ios, '10.0'

target 'CheckoutDemoBraintree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckoutDemoBraintree
  pod 'entervoCheckoutPluginBraintree','1.0.30'
  pod 'Braintree'
  pod 'BraintreeDropIn'

end
